---
openapi: 3.0.0
info:
  title: Super Admin
  description: Made for super admin
  version: 1.0.0
servers:
- url: /
paths:
  /stats:
    get:
      summary: Get Dashboard Stats
      description: Retrieves statistics for the super admin's dashboard.
      responses:
        "200":
          description: Successful stats retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
      security:
      - apiKeyAuth: []
  /auth/login:
    post:
      summary: Authenticate Super Admin
      description: Logs in a super admin.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400":
          description: Invalid username or password
  /forms:
    get:
      summary: Fetches list of pre-existing forms
      description: Retrieves a list of all forms available to the super admin.
      responses:
        "200":
          description: Successful retrieval of forms list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Forms'
        "401":
          description: Unauthorized (if authentication fails)
        "500":
          description: General server error
      security:
      - apiKeyAuth: []
  /addform:
    post:
      summary: Create a New Form
      description: Allows a super admin to create a new form.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFormRequest'
        required: true
      responses:
        "201":
          description: Form created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormIdResponse'
        "400":
          description: "Bad Request (e.g., invalid form structure)"
      security:
      - apiKeyAuth: []
  /forms/{formId}/default:
    put:
      summary: Set Form as Default
      description: Marks an existing form as the default form.
      parameters:
      - name: formId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Form successfully marked as default
        "400":
          description: "Bad Request (e.g., invalid form ID)"
        "404":
          description: Form not found
      security:
      - apiKeyAuth: []
  /auth/logout:
    post:
      summary: Logout Super Admin
      description: Logs out a super admin.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: You are logged out!
  /forms/{formId}:
    get:
      summary: Get Form Details
      description: Fetches the complete details of a specific form.
      parameters:
      - name: formId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Successful form retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forms'
        "404":
          description: Form not found
        "500":
          description: Server error
      security:
      - apiKeyAuth: []
    put:
      summary: Update Existing Form
      description: Allows a super admin to modify an existing form.
      parameters:
      - name: formId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFormRequest'
        required: true
      responses:
        "200":
          description: Form updated successfully
        "400":
          description: "Bad Request (e.g., invalid data, missing fields)"
        "404":
          description: Form not found
      security:
      - apiKeyAuth: []
components:
  schemas:
    StatsResponse:
      type: object
      properties:
        totalUsers:
          type: integer
        activeForms:
          type: integer
    LoginRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
    LoginResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    Forms:
      type: object
      properties:
        formId:
          type: integer
        formName:
          type: string
        createdAt:
          type: string
          format: date-time
        ICD10code:
          type: integer
      description: Stores all the pre-existing Forms
    FormIdResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    CreateFormRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fields:
          type: object
      description: Includes basic requirements of a form
    UpdateFormRequest:
      type: object
      properties:
        formName:
          type: string
    inline_response_200:
      type: object
      properties:
        DistrictId:
          type: integer
        DistrictStats:
          type: object
    inline_response_400:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
